config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home/index"

  resources :passwords, param: :token
  resource :session

  get "projects/new_form", to: "projects#new_form", as: "new_project_form"
  resources :projects do
    member do
      post "like", to: "projects#create_like"
      delete "like", to: "projects#destroy_like"
    end
  end

  get "users/confirm_email", to: "users#confirm_email", as: "confirm_user_email" # can't use POST because mail
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :rubygems
  has_many :project_likes, dependent: :destroy
  has_many :likers, through: :project_likes, source: :user

  validate :validate_rubygems
  validates :prompt, presence: true
  validates_url :homepage_url, allow_nil: true

  scope :published, -> { where.not(homepage_url: nil) }

  def published?
    homepage_url.present?
  end

  def visible_to?(user = nil)
    published? or self.user.id == user&.id
  end

  def liked_by?(user)
    likers.include? user
  end

  private

    def validate_rubygems
      errors.add(:rubygems, "must have exactly two, not #{rubygems.size}") unless rubygems.size == 2
      errors.add(:rubygems, "must not contain duplicates") unless rubygems.uniq.size == rubygems.size
    end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

require "securerandom"

class ProjectsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show new new_form ] # include new(_form) to reel users in
  before_action :resume_session # to set Current.user

  before_action :set_project, except: %i[ index new new_form create ]

  # GET /projects or /projects.json
  def index
    @projects = Project.published
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    if authenticated?
      @streamable = "chat_" + SecureRandom.uuid
      CreateProjectJob.perform_later @streamable
    end
  end

  def new_form
    @project = CreateProject.create.call # _slow_
    render formats: :turbo_stream
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = Current.user

    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project was successfully updated."
    else
      render :edit, status: :unprocessable_content
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed."
  end

  def create_like
    Current.user.like @project

    redirect_to @project, notice: "You liked this project"
  end

  def destroy_like
    Current.user.unlike @project

    redirect_to @project, notice: "You unliked this project"
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))

      head :forbidden unless @project.visible_to? Current.user
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :prompt, :homepage_url, rubygem_ids: [] ])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def rubygem_org_url(gem_name)
    gem_name = gem_name.name if gem_name.kind_of? Rubygem

    "https://rubygems.org/gems/#{gem_name}"
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div class="notification is-warning has-text-dark">
      <h4 class="has-text-dark"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Gems</h2>
  <%= form.fields :rubygem_ids, multiple: true do |rubygems_fields| %>
    <% project.rubygems.each do |rubygem| %>
      <%= rubygems_fields.hidden_field nil, id: nil, value: rubygem.id %>
      <%= link_to rubygem, rubygem_org_url(rubygem), class: "is-family-monospace", target: "_blank" %>
      <p><%= rubygem.description %></p>
    <% end %>
  <% end %>

  <h3>Prompt</h3>
  <%= form.hidden_field :prompt, value: project.prompt %>
  <% cache project.prompt do %>
    <%= markdown project.prompt %>
  <% end %>
  <% if project.errors[:prompt].any? %>
    <p class="help is-warning"><%= project.errors.full_messages_for(:prompt).join('.') %></p>
  <% end %>

  <% if project.persisted? %>
    <div class="field">
      <%= form.label :homepage_url, "Homepage", class: "label" %>
      <div class="control">
        <%= form.text_field :homepage_url, class: "input", placeholder: "Fill in a URL once you're done recording" %>
      </div>
      <p class="help">Adding a homepage will publish this project</p>
      <% if project.errors[:homepage_url].any? %>
        <p class="help is-warning"><%= project.errors.full_messages_for(:homepage_url).join('.') %></p>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
      <% if project.persisted? %>
        <%= form.submit "Publish", class: "button is-primary" %>
      <% else %>
      <%= form.submit "Gem to this", class: "button is-primary", disabled: !user_authenticated %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/_preview.html.erb
<div class="content">
  <p>
    <% project.rubygems.each_with_index do |rubygem, i| %>
      <%= link_to rubygem, rubygem_org_url(rubygem), class: "is-family-monospace", target: "_blank" %>

      <% if i < (project.rubygems.size - 1) %>,
      <% end %>
    <% end %>
  </p>

  <% cache project.prompt do %>
    <div class="line-clamp-2">
      <%= markdown project.prompt %>
    </div>
  <% end %>

  <% if project.homepage_url %>
    <p>
      <%= link_to "Homepage", project.homepage_url %>
    </p>
  <% end %>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="content">
  <h2>Gems</h2>
  <% project.rubygems.each do |rubygem| %>
    <%= link_to rubygem, rubygem_org_url(rubygem), class: "is-family-monospace", target: "_blank" %>
    <p><%= rubygem.description %></p>
  <% end %>

  <h2>Prompt</h2>
  <% cache project.prompt do %>
    <%= markdown project.prompt %>
  <% end %>

  <% if project.homepage_url %>
    <p>
      <%= link_to "Homepage", project.homepage_url, target: "_blank", rel: "noopener noreferrer" %>
    </p>
  <% end %>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="content">
  <h3>Editing project</h3>

  <%= render "form", project: @project, user_authenticated: authenticated? %>

  <br>

  <div>
    <%= link_to "Show this project", @project %> |
    <%= link_to "Back to projects", projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<div class="content">
  <h1>Published projects</h1>

  <div id="projects" class="block">
    <% @projects.each do |project| %>
      <div class="box">
        <%= render "preview", project: %>
        <p>
          <%= link_to "Show this project", project %>
        </p>
      </div>
    <% end %>
  </div>

  <%= link_to "New project", new_project_path, class: "button is-primary" %>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="content">
  <h1>New project</h1>

  <div id="new_project">
    <p>Hang in there, Noodle is thinking... 🥁</p>
  </div>

  <% if defined? @streamable %>
    <%= turbo_stream_from @streamable %> <%# CreateProjectJob will broadcast_replace_to %>
  <% else %>
    <%= turbo_frame_tag src: new_project_form_path %>
  <% end %>

  <% unless authenticated? %>
    <p class="mt-4">
      Sounds like fun? Then please <%= link_to "join up", new_user_path %> to start gemming!
    </p>
  <% end %>
</div>

app/views/projects/new_form.turbo_stream.erb
<%= turbo_stream.replace "new_project" do %>
  <%= render "form", project: @project, user_authenticated: false %>
<% end %>

app/views/projects/show.html.erb
<%= render @project %>

<% if @project.user == Current.user %>
  <div class="field is-grouped">
    <%= link_to "Edit", edit_project_path(@project), class: "button is-primary" %>
    <%= button_to "Delete", @project, method: :delete, class: "button is-warning" %>
  </div>
<% elsif authenticated? %>
  <div class="field is-grouped">
    <% name, method = Current.user.like?(@project) ? ["Unlike", :delete] : ["Like", :post] %>
    <%= button_to name, like_project_path, method:, class: "button is-primary" %>
  </div>
<% end %>