config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home/index"

  resources :passwords, param: :token
  resource :session

  get "projects/new_form", to: "projects#new_form", as: "new_project_form"
  resources :projects do
    member do
      post "like", to: "projects#create_like"
      delete "like", to: "projects#destroy_like"
    end
  end

  get "users/confirm_email", to: "users#confirm_email", as: "confirm_user_email" # can't use POST because mail
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gem Session 🤘" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="keywords" content="gem session, ruby, ruby gems, ruby programming, coding challenge, coding practice, programming, developer creativity">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="container is-max-tablet">
        <div class="navbar-brand">
          <%= link_to "Gem Session 🤘", home_index_path, class: "navbar-item is-size-4 has-text-weight-bold" %>
        </div>

        <div class="navbar-start">
          <%= link_to "Projects", projects_path, class: "navbar-item" %>
        </div>

        <div class="navbar-end">
          <div class="buttons">
            <% if authenticated? %>
              <%= link_to "My profile", user_path(Current.user), class: "button is-primary" %>
              <%= button_to "Jack out", session_path, method: :delete, class: "button is-light" %>
            <% else %>
              <%= link_to "Join up", new_user_path, class: "button is-primary" %>
              <%= link_to "Jack in", new_session_path, class: "button is-light" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <% if notice.present? or alert.present? %>
      <section class="notification has-text-centered <%= notice.present? ? "is-primary" : "is-danger" %>">
        <%= notice || alert %>
      </section>
    <% end %>

    <section class="section">
      <div class="container is-max-tablet">
        <%= yield %>
      </div>
    </section>
  </body>
</html>